# Generated by Django 5.0.6 on 2024-05-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskandtarget', '0002_rename_owner_task_assigned_to_task_assigned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_by',
            field=models.CharField(default='superadmin', max_length=20),
        ),
    ]
