# Generated by Django 5.0.6 on 2024-05-17 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_department_created'),
        ('worker', '0002_worker_is_admin_alter_worker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.department'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='designation',
            field=models.ForeignKey(default='staff', on_delete=django.db.models.deletion.CASCADE, to='superadmin.designation'),
        ),
    ]
